[package]
name = "machine-project-2"
version = "0.1.0"
authors = ["Jonah George <jonah.george@me.com>"]

[dependencies]
rand = "*"
tarpc = "0.6.0"
clap = "*"

[[bin]]
name = "machine-project-2"
path = "src/main.rs"
